# This file was automagically generated by mbed.org. For more information, 
# see http://mbed.org/handbook/Exporting-to-GCC-ARM-Embedded

###############################################################################
# Boiler-plate

# cross-platform directory manipulation
ifeq ($(shell echo $$OS),$$OS)
    MAKEDIR = if not exist "$(1)" mkdir "$(1)"
    RM = rmdir /S /Q "$(1)"
else
    MAKEDIR = '$(SHELL)' -c "mkdir -p \"$(1)\""
    RM = '$(SHELL)' -c "rm -rf \"$(1)\""
endif

OBJDIR := BUILD
# Move to the build directory
ifeq (,$(filter $(OBJDIR),$(notdir $(CURDIR))))
.SUFFIXES:
mkfile_path := $(abspath $(lastword $(MAKEFILE_LIST)))
MAKETARGET = '$(MAKE)' --no-print-directory -C $(OBJDIR) -f '$(mkfile_path)' \
		'SRCDIR=$(CURDIR)' $(MAKECMDGOALS)
.PHONY: $(OBJDIR) clean
all:
	+@$(call MAKEDIR,$(OBJDIR))
	+@$(MAKETARGET)
$(OBJDIR): all
Makefile : ;
% :: $(OBJDIR) ; :
clean :
	$(call RM,$(OBJDIR))

else

# trick rules into thinking we are in the root, when we are in the bulid dir
VPATH = ..

# Boiler-plate
###############################################################################
# Project settings

PROJECT := mbed-os-example-ble-GAPButton


# Project settings
###############################################################################
# Objects and Paths

OBJECTS += mbed-os/drivers/AnalogIn.o
OBJECTS += mbed-os/drivers/BusIn.o
OBJECTS += mbed-os/drivers/BusInOut.o
OBJECTS += mbed-os/drivers/BusOut.o
OBJECTS += mbed-os/drivers/CAN.o
OBJECTS += mbed-os/drivers/Ethernet.o
OBJECTS += mbed-os/drivers/FlashIAP.o
OBJECTS += mbed-os/drivers/I2C.o
OBJECTS += mbed-os/drivers/I2CSlave.o
OBJECTS += mbed-os/drivers/InterruptIn.o
OBJECTS += mbed-os/drivers/InterruptManager.o
OBJECTS += mbed-os/drivers/RawSerial.o
OBJECTS += mbed-os/drivers/SPI.o
OBJECTS += mbed-os/drivers/SPISlave.o
OBJECTS += mbed-os/drivers/Serial.o
OBJECTS += mbed-os/drivers/SerialBase.o
OBJECTS += mbed-os/drivers/Ticker.o
OBJECTS += mbed-os/drivers/Timeout.o
OBJECTS += mbed-os/drivers/Timer.o
OBJECTS += mbed-os/drivers/TimerEvent.o
OBJECTS += mbed-os/drivers/UARTSerial.o
OBJECTS += mbed-os/events/EventQueue.o
OBJECTS += mbed-os/events/equeue/equeue.o
OBJECTS += mbed-os/events/equeue/equeue_mbed.o
OBJECTS += mbed-os/events/equeue/equeue_posix.o
OBJECTS += mbed-os/events/mbed_shared_queues.o
OBJECTS += mbed-os/features/FEATURE_BLE/source/BLE.o
OBJECTS += mbed-os/features/FEATURE_BLE/source/BLEInstanceBase.o
OBJECTS += mbed-os/features/FEATURE_BLE/source/DiscoveredCharacteristic.o
OBJECTS += mbed-os/features/FEATURE_BLE/source/GapScanningParams.o
OBJECTS += mbed-os/features/FEATURE_BLE/source/generic/GenericGattClient.o
OBJECTS += mbed-os/features/FEATURE_BLE/source/services/DFUService.o
OBJECTS += mbed-os/features/FEATURE_BLE/source/services/UARTService.o
OBJECTS += mbed-os/features/FEATURE_BLE/source/services/URIBeaconConfigService.o
OBJECTS += mbed-os/features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source/btle/btle.o
OBJECTS += mbed-os/features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source/btle/btle_discovery.o
OBJECTS += mbed-os/features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source/btle/btle_gap.o
OBJECTS += mbed-os/features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source/btle/btle_security.o
OBJECTS += mbed-os/features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source/btle/btle_security_pm.o
OBJECTS += mbed-os/features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source/btle/custom/custom_helper.o
OBJECTS += mbed-os/features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source/nRF5xCharacteristicDescriptorDiscoverer.o
OBJECTS += mbed-os/features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source/nRF5xDiscoveredCharacteristic.o
OBJECTS += mbed-os/features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source/nRF5xGap.o
OBJECTS += mbed-os/features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source/nRF5xGattClient.o
OBJECTS += mbed-os/features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source/nRF5xGattServer.o
OBJECTS += mbed-os/features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source/nRF5xServiceDiscovery.o
OBJECTS += mbed-os/features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source/nRF5xn.o
OBJECTS += mbed-os/features/filesystem/Dir.o
OBJECTS += mbed-os/features/filesystem/File.o
OBJECTS += mbed-os/features/filesystem/FileSystem.o
OBJECTS += mbed-os/features/filesystem/bd/ChainingBlockDevice.o
OBJECTS += mbed-os/features/filesystem/bd/ExhaustibleBlockDevice.o
OBJECTS += mbed-os/features/filesystem/bd/HeapBlockDevice.o
OBJECTS += mbed-os/features/filesystem/bd/MBRBlockDevice.o
OBJECTS += mbed-os/features/filesystem/bd/ObservingBlockDevice.o
OBJECTS += mbed-os/features/filesystem/bd/ProfilingBlockDevice.o
OBJECTS += mbed-os/features/filesystem/bd/ReadOnlyBlockDevice.o
OBJECTS += mbed-os/features/filesystem/bd/SlicingBlockDevice.o
OBJECTS += mbed-os/features/filesystem/fat/ChaN/ff.o
OBJECTS += mbed-os/features/filesystem/fat/ChaN/ffunicode.o
OBJECTS += mbed-os/features/filesystem/fat/FATFileSystem.o
OBJECTS += mbed-os/features/filesystem/littlefs/LittleFileSystem.o
OBJECTS += mbed-os/features/filesystem/littlefs/TESTS_COMMON/atomic_usage.o
OBJECTS += mbed-os/features/filesystem/littlefs/littlefs/lfs.o
OBJECTS += mbed-os/features/filesystem/littlefs/littlefs/lfs_util.o
OBJECTS += mbed-os/features/frameworks/greentea-client/source/greentea_metrics.o
OBJECTS += mbed-os/features/frameworks/greentea-client/source/greentea_serial.o
OBJECTS += mbed-os/features/frameworks/greentea-client/source/greentea_test_env.o
OBJECTS += mbed-os/features/frameworks/unity/source/unity.o
OBJECTS += mbed-os/features/frameworks/utest/mbed-utest-shim.o
OBJECTS += mbed-os/features/frameworks/utest/source/unity_handler.o
OBJECTS += mbed-os/features/frameworks/utest/source/utest_case.o
OBJECTS += mbed-os/features/frameworks/utest/source/utest_default_handlers.o
OBJECTS += mbed-os/features/frameworks/utest/source/utest_greentea_handlers.o
OBJECTS += mbed-os/features/frameworks/utest/source/utest_harness.o
OBJECTS += mbed-os/features/frameworks/utest/source/utest_shim.o
OBJECTS += mbed-os/features/frameworks/utest/source/utest_stack_trace.o
OBJECTS += mbed-os/features/frameworks/utest/source/utest_types.o
OBJECTS += mbed-os/features/mbedtls/platform/src/mbed_trng.o
OBJECTS += mbed-os/features/mbedtls/src/aes.o
OBJECTS += mbed-os/features/mbedtls/src/aesni.o
OBJECTS += mbed-os/features/mbedtls/src/arc4.o
OBJECTS += mbed-os/features/mbedtls/src/asn1parse.o
OBJECTS += mbed-os/features/mbedtls/src/asn1write.o
OBJECTS += mbed-os/features/mbedtls/src/base64.o
OBJECTS += mbed-os/features/mbedtls/src/bignum.o
OBJECTS += mbed-os/features/mbedtls/src/blowfish.o
OBJECTS += mbed-os/features/mbedtls/src/camellia.o
OBJECTS += mbed-os/features/mbedtls/src/ccm.o
OBJECTS += mbed-os/features/mbedtls/src/certs.o
OBJECTS += mbed-os/features/mbedtls/src/cipher.o
OBJECTS += mbed-os/features/mbedtls/src/cipher_wrap.o
OBJECTS += mbed-os/features/mbedtls/src/cmac.o
OBJECTS += mbed-os/features/mbedtls/src/ctr_drbg.o
OBJECTS += mbed-os/features/mbedtls/src/debug.o
OBJECTS += mbed-os/features/mbedtls/src/des.o
OBJECTS += mbed-os/features/mbedtls/src/dhm.o
OBJECTS += mbed-os/features/mbedtls/src/ecdh.o
OBJECTS += mbed-os/features/mbedtls/src/ecdsa.o
OBJECTS += mbed-os/features/mbedtls/src/ecjpake.o
OBJECTS += mbed-os/features/mbedtls/src/ecp.o
OBJECTS += mbed-os/features/mbedtls/src/ecp_curves.o
OBJECTS += mbed-os/features/mbedtls/src/entropy.o
OBJECTS += mbed-os/features/mbedtls/src/entropy_poll.o
OBJECTS += mbed-os/features/mbedtls/src/error.o
OBJECTS += mbed-os/features/mbedtls/src/gcm.o
OBJECTS += mbed-os/features/mbedtls/src/havege.o
OBJECTS += mbed-os/features/mbedtls/src/hmac_drbg.o
OBJECTS += mbed-os/features/mbedtls/src/md.o
OBJECTS += mbed-os/features/mbedtls/src/md2.o
OBJECTS += mbed-os/features/mbedtls/src/md4.o
OBJECTS += mbed-os/features/mbedtls/src/md5.o
OBJECTS += mbed-os/features/mbedtls/src/md_wrap.o
OBJECTS += mbed-os/features/mbedtls/src/memory_buffer_alloc.o
OBJECTS += mbed-os/features/mbedtls/src/net_sockets.o
OBJECTS += mbed-os/features/mbedtls/src/oid.o
OBJECTS += mbed-os/features/mbedtls/src/padlock.o
OBJECTS += mbed-os/features/mbedtls/src/pem.o
OBJECTS += mbed-os/features/mbedtls/src/pk.o
OBJECTS += mbed-os/features/mbedtls/src/pk_wrap.o
OBJECTS += mbed-os/features/mbedtls/src/pkcs11.o
OBJECTS += mbed-os/features/mbedtls/src/pkcs12.o
OBJECTS += mbed-os/features/mbedtls/src/pkcs5.o
OBJECTS += mbed-os/features/mbedtls/src/pkparse.o
OBJECTS += mbed-os/features/mbedtls/src/pkwrite.o
OBJECTS += mbed-os/features/mbedtls/src/platform.o
OBJECTS += mbed-os/features/mbedtls/src/ripemd160.o
OBJECTS += mbed-os/features/mbedtls/src/rsa.o
OBJECTS += mbed-os/features/mbedtls/src/sha1.o
OBJECTS += mbed-os/features/mbedtls/src/sha256.o
OBJECTS += mbed-os/features/mbedtls/src/sha512.o
OBJECTS += mbed-os/features/mbedtls/src/ssl_cache.o
OBJECTS += mbed-os/features/mbedtls/src/ssl_ciphersuites.o
OBJECTS += mbed-os/features/mbedtls/src/ssl_cli.o
OBJECTS += mbed-os/features/mbedtls/src/ssl_cookie.o
OBJECTS += mbed-os/features/mbedtls/src/ssl_srv.o
OBJECTS += mbed-os/features/mbedtls/src/ssl_ticket.o
OBJECTS += mbed-os/features/mbedtls/src/ssl_tls.o
OBJECTS += mbed-os/features/mbedtls/src/threading.o
OBJECTS += mbed-os/features/mbedtls/src/timing.o
OBJECTS += mbed-os/features/mbedtls/src/version.o
OBJECTS += mbed-os/features/mbedtls/src/version_features.o
OBJECTS += mbed-os/features/mbedtls/src/x509.o
OBJECTS += mbed-os/features/mbedtls/src/x509_create.o
OBJECTS += mbed-os/features/mbedtls/src/x509_crl.o
OBJECTS += mbed-os/features/mbedtls/src/x509_crt.o
OBJECTS += mbed-os/features/mbedtls/src/x509_csr.o
OBJECTS += mbed-os/features/mbedtls/src/x509write_crt.o
OBJECTS += mbed-os/features/mbedtls/src/x509write_csr.o
OBJECTS += mbed-os/features/mbedtls/src/xtea.o
OBJECTS += mbed-os/features/netsocket/NetworkInterface.o
OBJECTS += mbed-os/features/netsocket/NetworkStack.o
OBJECTS += mbed-os/features/netsocket/Socket.o
OBJECTS += mbed-os/features/netsocket/SocketAddress.o
OBJECTS += mbed-os/features/netsocket/TCPServer.o
OBJECTS += mbed-os/features/netsocket/TCPSocket.o
OBJECTS += mbed-os/features/netsocket/UDPSocket.o
OBJECTS += mbed-os/features/netsocket/WiFiAccessPoint.o
OBJECTS += mbed-os/features/netsocket/cellular/generic_modem_driver/OnboardCellularInterface.o
OBJECTS += mbed-os/features/netsocket/cellular/generic_modem_driver/PPPCellularInterface.o
OBJECTS += mbed-os/features/netsocket/cellular/generic_modem_driver/UARTCellularInterface.o
OBJECTS += mbed-os/features/netsocket/nsapi_dns.o
OBJECTS += mbed-os/hal/mbed_flash_api.o
OBJECTS += mbed-os/hal/mbed_gpio.o
OBJECTS += mbed-os/hal/mbed_lp_ticker_api.o
OBJECTS += mbed-os/hal/mbed_pinmap_common.o
OBJECTS += mbed-os/hal/mbed_sleep_manager.o
OBJECTS += mbed-os/hal/mbed_ticker_api.o
OBJECTS += mbed-os/hal/mbed_us_ticker_api.o
OBJECTS += mbed-os/platform/ATCmdParser.o
OBJECTS += mbed-os/platform/CallChain.o
OBJECTS += mbed-os/platform/FileBase.o
OBJECTS += mbed-os/platform/FileHandle.o
OBJECTS += mbed-os/platform/FilePath.o
OBJECTS += mbed-os/platform/FileSystemHandle.o
OBJECTS += mbed-os/platform/LocalFileSystem.o
OBJECTS += mbed-os/platform/Stream.o
OBJECTS += mbed-os/platform/mbed_alloc_wrappers.o
OBJECTS += mbed-os/platform/mbed_application.o
OBJECTS += mbed-os/platform/mbed_assert.o
OBJECTS += mbed-os/platform/mbed_board.o
OBJECTS += mbed-os/platform/mbed_critical.o
OBJECTS += mbed-os/platform/mbed_error.o
OBJECTS += mbed-os/platform/mbed_interface.o
OBJECTS += mbed-os/platform/mbed_mem_trace.o
OBJECTS += mbed-os/platform/mbed_mktime.o
OBJECTS += mbed-os/platform/mbed_poll.o
OBJECTS += mbed-os/platform/mbed_retarget.o
OBJECTS += mbed-os/platform/mbed_rtc_time.o
OBJECTS += mbed-os/platform/mbed_sdk_boot.o
OBJECTS += mbed-os/platform/mbed_semihost_api.o
OBJECTS += mbed-os/platform/mbed_stats.o
OBJECTS += mbed-os/platform/mbed_wait_api_no_rtos.o
OBJECTS += mbed-os/platform/mbed_wait_api_rtos.o
OBJECTS += mbed-os/rtos/ConditionVariable.o
OBJECTS += mbed-os/rtos/EventFlags.o
OBJECTS += mbed-os/rtos/Mutex.o
OBJECTS += mbed-os/rtos/RtosTimer.o
OBJECTS += mbed-os/rtos/Semaphore.o
OBJECTS += mbed-os/rtos/TARGET_CORTEX/mbed_boot.o
OBJECTS += mbed-os/rtos/TARGET_CORTEX/mbed_rtx_handlers.o
OBJECTS += mbed-os/rtos/TARGET_CORTEX/mbed_rtx_idle.o
OBJECTS += mbed-os/rtos/TARGET_CORTEX/rtx4/cmsis_os1.o
OBJECTS += mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Config/RTX_Config.o
OBJECTS += mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_GCC/TARGET_M0/irq_cm0.o
OBJECTS += mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rt_OsEventObserver.o
OBJECTS += mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_delay.o
OBJECTS += mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_evflags.o
OBJECTS += mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_evr.o
OBJECTS += mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_kernel.o
OBJECTS += mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_lib.o
OBJECTS += mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_memory.o
OBJECTS += mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_mempool.o
OBJECTS += mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_msgqueue.o
OBJECTS += mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_mutex.o
OBJECTS += mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_semaphore.o
OBJECTS += mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_system.o
OBJECTS += mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_thread.o
OBJECTS += mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_timer.o
OBJECTS += mbed-os/rtos/TARGET_CORTEX/rtx5/Source/os_systick.o
OBJECTS += mbed-os/rtos/TARGET_CORTEX/rtx5/Source/os_tick_ptim.o
OBJECTS += mbed-os/rtos/Thread.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/analogin_api.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/device/TOOLCHAIN_GCC_ARM/startup_NRF51822.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/device/cmsis_nvic.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/device/system_nrf51.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/pwmout_api.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/sdk/drivers_nrf/adc/nrf_drv_adc.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/ble_advertising/ble_advertising.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/ble_db_discovery/ble_db_discovery.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/ble_debug_assert_handler/ble_debug_assert_handler.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/ble_dtm/ble_dtm.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/ble_racp/ble_racp.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/ble_radio_notification/ble_radio_notification.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/ble_services/ble_dfu/ble_dfu.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/common/ble_advdata.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/common/ble_conn_state.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/common/ble_srv_common.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/device_manager/device_manager_peripheral.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/peer_manager/gatt_cache_manager.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/peer_manager/gattc_cache_manager.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/peer_manager/gatts_cache_manager.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/peer_manager/id_manager.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/peer_manager/peer_data.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/peer_manager/peer_data_storage.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/peer_manager/peer_database.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/peer_manager/peer_id.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/peer_manager/peer_manager.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/peer_manager/pm_buffer.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/peer_manager/pm_mutex.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/peer_manager/security_dispatcher.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/peer_manager/security_manager.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/ble_flash/ble_flash.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/clock/nrf_drv_clock.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/common/nrf_drv_common.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/delay/nrf_delay.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/gpiote/nrf_drv_gpiote.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/hal/nrf_adc.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/hal/nrf_ecb.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/hal/nrf_nvmc.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/hal/nrf_saadc.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/ppi/nrf_drv_ppi.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/pstorage/pstorage.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/spi_master/nrf_drv_spi.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/spi_slave/nrf_drv_spis.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/timer/nrf_drv_timer.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/bootloader_dfu/bootloader_util.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/bootloader_dfu/dfu_app_handler.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/bootloader_dfu/dfu_init_template.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/crc16/crc16.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/fds/fds.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/fstorage/fstorage.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/fstorage/fstorage_nosd.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/hci/hci_mem_pool.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/pwm/app_pwm.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/scheduler/app_scheduler.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/trace/app_trace.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/util/app_error.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/util/app_error_weak.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/util/app_util_platform.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/util/nrf_assert.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/util/nrf_log.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/util/sdk_mapped_flags.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/softdevice/common/softdevice_handler/softdevice_handler.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/softdevice/common/softdevice_handler/softdevice_handler_appsh.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/flash_api.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/gpio_api.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/i2c_api.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/lp_ticker.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/nordic_critical.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/pinmap.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/port_api.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/reloc_vector_table.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/rtc_api.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/serial_api.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/sleep.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/spi_api.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/trng_api.o
OBJECTS += mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/us_ticker.o
OBJECTS += source/main.o
OBJECTS += source/SHTx/sht15.o
OBJECTS += source/SHTx/i2c.o


INCLUDE_PATHS += -I../
INCLUDE_PATHS += -I../.
INCLUDE_PATHS += -I../img
INCLUDE_PATHS += -I../mbed-os/.
INCLUDE_PATHS += -I../mbed-os/cmsis
INCLUDE_PATHS += -I../mbed-os/cmsis/TARGET_CORTEX_M
INCLUDE_PATHS += -I../mbed-os/drivers
INCLUDE_PATHS += -I../mbed-os/events
INCLUDE_PATHS += -I../mbed-os/events/equeue
INCLUDE_PATHS += -I../mbed-os/features
INCLUDE_PATHS += -I../mbed-os/features/FEATURE_BLE
INCLUDE_PATHS += -I../mbed-os/features/FEATURE_BLE/ble
INCLUDE_PATHS += -I../mbed-os/features/FEATURE_BLE/ble/generic
INCLUDE_PATHS += -I../mbed-os/features/FEATURE_BLE/ble/pal
INCLUDE_PATHS += -I../mbed-os/features/FEATURE_BLE/ble/services
INCLUDE_PATHS += -I../mbed-os/features/FEATURE_BLE/source
INCLUDE_PATHS += -I../mbed-os/features/FEATURE_BLE/source/generic
INCLUDE_PATHS += -I../mbed-os/features/FEATURE_BLE/source/services
INCLUDE_PATHS += -I../mbed-os/features/FEATURE_BLE/targets
INCLUDE_PATHS += -I../mbed-os/features/FEATURE_BLE/targets/TARGET_NORDIC
INCLUDE_PATHS += -I../mbed-os/features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5
INCLUDE_PATHS += -I../mbed-os/features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source
INCLUDE_PATHS += -I../mbed-os/features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source/btle
INCLUDE_PATHS += -I../mbed-os/features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source/btle/custom
INCLUDE_PATHS += -I../mbed-os/features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source/common
INCLUDE_PATHS += -I../mbed-os/features/filesystem
INCLUDE_PATHS += -I../mbed-os/features/filesystem/bd
INCLUDE_PATHS += -I../mbed-os/features/filesystem/fat
INCLUDE_PATHS += -I../mbed-os/features/filesystem/fat/ChaN
INCLUDE_PATHS += -I../mbed-os/features/filesystem/littlefs
INCLUDE_PATHS += -I../mbed-os/features/filesystem/littlefs/TESTS_COMMON
INCLUDE_PATHS += -I../mbed-os/features/filesystem/littlefs/littlefs
INCLUDE_PATHS += -I../mbed-os/features/frameworks
INCLUDE_PATHS += -I../mbed-os/features/frameworks/greentea-client
INCLUDE_PATHS += -I../mbed-os/features/frameworks/greentea-client/greentea-client
INCLUDE_PATHS += -I../mbed-os/features/frameworks/greentea-client/source
INCLUDE_PATHS += -I../mbed-os/features/frameworks/unity
INCLUDE_PATHS += -I../mbed-os/features/frameworks/unity/source
INCLUDE_PATHS += -I../mbed-os/features/frameworks/unity/unity
INCLUDE_PATHS += -I../mbed-os/features/frameworks/utest
INCLUDE_PATHS += -I../mbed-os/features/frameworks/utest/source
INCLUDE_PATHS += -I../mbed-os/features/frameworks/utest/utest
INCLUDE_PATHS += -I../mbed-os/features/mbedtls
INCLUDE_PATHS += -I../mbed-os/features/mbedtls/importer
INCLUDE_PATHS += -I../mbed-os/features/mbedtls/inc
INCLUDE_PATHS += -I../mbed-os/features/mbedtls/inc/mbedtls
INCLUDE_PATHS += -I../mbed-os/features/mbedtls/platform
INCLUDE_PATHS += -I../mbed-os/features/mbedtls/platform/inc
INCLUDE_PATHS += -I../mbed-os/features/mbedtls/platform/src
INCLUDE_PATHS += -I../mbed-os/features/mbedtls/src
INCLUDE_PATHS += -I../mbed-os/features/mbedtls/targets
INCLUDE_PATHS += -I../mbed-os/features/nanostack
INCLUDE_PATHS += -I../mbed-os/features/netsocket
INCLUDE_PATHS += -I../mbed-os/features/netsocket/cellular
INCLUDE_PATHS += -I../mbed-os/features/netsocket/cellular/generic_modem_driver
INCLUDE_PATHS += -I../mbed-os/features/netsocket/cellular/utils
INCLUDE_PATHS += -I../mbed-os/features/storage
INCLUDE_PATHS += -I../mbed-os/hal
INCLUDE_PATHS += -I../mbed-os/hal/storage_abstraction
INCLUDE_PATHS += -I../mbed-os/platform
INCLUDE_PATHS += -I../mbed-os/rtos
INCLUDE_PATHS += -I../mbed-os/rtos/TARGET_CORTEX
INCLUDE_PATHS += -I../mbed-os/rtos/TARGET_CORTEX/rtx4
INCLUDE_PATHS += -I../mbed-os/rtos/TARGET_CORTEX/rtx5
INCLUDE_PATHS += -I../mbed-os/rtos/TARGET_CORTEX/rtx5/Include
INCLUDE_PATHS += -I../mbed-os/rtos/TARGET_CORTEX/rtx5/RTX
INCLUDE_PATHS += -I../mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Config
INCLUDE_PATHS += -I../mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Include
INCLUDE_PATHS += -I../mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source
INCLUDE_PATHS += -I../mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_GCC
INCLUDE_PATHS += -I../mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_GCC/TARGET_M0
INCLUDE_PATHS += -I../mbed-os/rtos/TARGET_CORTEX/rtx5/Source
INCLUDE_PATHS += -I../mbed-os/targets
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/TARGET_NRF51_DK
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/device
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/device/TOOLCHAIN_GCC_ARM
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/device/TOOLCHAIN_GCC_ARM/TARGET_MCU_NORDIC_32K
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/sdk
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/sdk/drivers_nrf
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/sdk/drivers_nrf/adc
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/sdk/softdevice
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/sdk/softdevice/s130
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/sdk/softdevice/s130/headers
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/sdk/softdevice/s130/headers/nrf51
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/sdk/softdevice/s130/hex
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/sdk_patch
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/ble_advertising
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/ble_db_discovery
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/ble_debug_assert_handler
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/ble_dtm
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/ble_error_log
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/ble_racp
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/ble_radio_notification
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/ble_services
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/ble_services/ble_dfu
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/common
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/device_manager
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/device_manager/config
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/peer_manager
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/device
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/ble_flash
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/clock
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/common
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/config
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/delay
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/gpiote
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/hal
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/ppi
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/pstorage
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/pstorage/config
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/spi_master
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/spi_slave
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/timer
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/bootloader_dfu
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/bootloader_dfu/hci_transport
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/crc16
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/experimental_section_vars
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/fds
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/fds/config
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/fstorage
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/fstorage/config
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/hci
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/hci/config
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/pwm
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/scheduler
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/trace
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/util
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/softdevice
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/softdevice/common
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/softdevice/common/softdevice_handler
INCLUDE_PATHS += -I../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/porting_tools
INCLUDE_PATHS += -I../shields
INCLUDE_PATHS += -I../source

LIBRARY_PATHS :=
LIBRARIES :=
LINKER_SCRIPT ?= ../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/device/TOOLCHAIN_GCC_ARM/TARGET_MCU_NORDIC_32K/NRF51822.ld

# Objects and Paths
###############################################################################
# Tools and Flags

AS      = 'arm-none-eabi-gcc' '-x' 'assembler-with-cpp' '-c' '-Wall' '-Wextra' '-Wno-unused-parameter' '-Wno-missing-field-initializers' '-fmessage-length=0' '-fno-exceptions' '-fno-builtin' '-ffunction-sections' '-fdata-sections' '-funsigned-char' '-MMD' '-fno-delete-null-pointer-checks' '-fomit-frame-pointer' '-Os' '-mcpu=cortex-m0' '-mthumb'
CC      = 'arm-none-eabi-gcc' '-std=gnu99' '-c' '-Wall' '-Wextra' '-Wno-unused-parameter' '-Wno-missing-field-initializers' '-fmessage-length=0' '-fno-exceptions' '-fno-builtin' '-ffunction-sections' '-fdata-sections' '-funsigned-char' '-MMD' '-fno-delete-null-pointer-checks' '-fomit-frame-pointer' '-Os' '-mcpu=cortex-m0' '-mthumb'
CPP     = 'arm-none-eabi-g++' '-std=gnu++98' '-fno-rtti' '-Wvla' '-c' '-Wall' '-Wextra' '-Wno-unused-parameter' '-Wno-missing-field-initializers' '-fmessage-length=0' '-fno-exceptions' '-fno-builtin' '-ffunction-sections' '-fdata-sections' '-funsigned-char' '-MMD' '-fno-delete-null-pointer-checks' '-fomit-frame-pointer' '-Os' '-mcpu=cortex-m0' '-mthumb'
LD      = 'arm-none-eabi-gcc'
ELF2BIN = 'arm-none-eabi-objcopy'
PREPROC = 'arm-none-eabi-cpp' '-E' '-P' '-Wl,--gc-sections' '-Wl,--wrap,main' '-Wl,--wrap,_malloc_r' '-Wl,--wrap,_free_r' '-Wl,--wrap,_realloc_r' '-Wl,--wrap,_memalign_r' '-Wl,--wrap,_calloc_r' '-Wl,--wrap,exit' '-Wl,--wrap,atexit' '-Wl,-n' '-mcpu=cortex-m0' '-mthumb'

SREC_CAT = srec_cat

C_FLAGS += -std=gnu99
C_FLAGS += -D__CORTEX_M0
C_FLAGS += -DNRF51
C_FLAGS += -D__MBED__=1
C_FLAGS += -DTARGET_LIKE_MBED
C_FLAGS += -DTARGET_NRF51822
C_FLAGS += -DDEVICE_PORTINOUT=1
C_FLAGS += -D__MBED_CMSIS_RTOS_CM
C_FLAGS += -DDEVICE_LOWPOWERTIMER=1
C_FLAGS += -DDEVICE_RTC=1
C_FLAGS += -DTOOLCHAIN_object
C_FLAGS += -DDEVICE_SERIAL_ASYNCH=1
C_FLAGS += -D__CMSIS_RTOS
C_FLAGS += -DTARGET_MCU_NRF51822_UNIFIED
C_FLAGS += -DTOOLCHAIN_GCC
C_FLAGS += -DDEVICE_I2C_ASYNCH=1
C_FLAGS += -DTARGET_CORTEX_M
C_FLAGS += -DTARGET_SDK11
C_FLAGS += -DARM_MATH_CM0
C_FLAGS += -DTARGET_UVISOR_UNSUPPORTED
C_FLAGS += -DTARGET_NRF5
C_FLAGS += -DFEATURE_BLE=1
C_FLAGS += -DTARGET_M0
C_FLAGS += -DTARGET_MCU_NRF51
C_FLAGS += -DCMSIS_VECTAB_VIRTUAL
C_FLAGS += -DTARGET_MCU_NRF51_UNIFIED
C_FLAGS += -DMBED_TICKLESS
C_FLAGS += -DDEVICE_INTERRUPTIN=1
C_FLAGS += -DTARGET_CORTEX
C_FLAGS += -DDEVICE_I2C=1
C_FLAGS += -DDEVICE_PORTOUT=1
C_FLAGS += -DDEVICE_SERIAL=1
C_FLAGS += -DDEVICE_SPI_ASYNCH=1
C_FLAGS += -DTARGET_FF_ARDUINO
C_FLAGS += -DDEVICE_PORTIN=1
C_FLAGS += -DTARGET_RELEASE
C_FLAGS += -DTARGET_NORDIC
C_FLAGS += -DDEVICE_SERIAL_FC=1
C_FLAGS += -DBLE_STACK_SUPPORT_REQD
C_FLAGS += -DTARGET_MCU_NRF51_32K_UNIFIED
C_FLAGS += -DTARGET_NRF51_DK
C_FLAGS += -DDEVICE_SLEEP=1
C_FLAGS += -DTOOLCHAIN_GCC_ARM
C_FLAGS += -DTARGET_MCU_NRF51822
C_FLAGS += -DMBED_BUILD_TIMESTAMP=1515055061.66
C_FLAGS += -DTARGET_MCU_NORDIC_32K
C_FLAGS += -DSOFTDEVICE_PRESENT
C_FLAGS += -DNO_SYSTICK
C_FLAGS += -DDEVICE_SPI=1
C_FLAGS += -DCMSIS_VECTAB_VIRTUAL_HEADER_FILE=\"cmsis_nvic.h\"
C_FLAGS += -DDEVICE_SPISLAVE=1
C_FLAGS += -DDEVICE_ANALOGIN=1
C_FLAGS += -DDEVICE_PWMOUT=1
C_FLAGS += -DS130
C_FLAGS += -DTARGET_LIKE_CORTEX_M0
C_FLAGS += -DTARGET_MCU_NRF51_32K
C_FLAGS += -include
C_FLAGS += mbed_config.h

CXX_FLAGS += -std=gnu++98
CXX_FLAGS += -fno-rtti
CXX_FLAGS += -Wvla
CXX_FLAGS += -D__CORTEX_M0
CXX_FLAGS += -DNRF51
CXX_FLAGS += -D__MBED__=1
CXX_FLAGS += -DTARGET_LIKE_MBED
CXX_FLAGS += -DTARGET_NRF51822
CXX_FLAGS += -DDEVICE_PORTINOUT=1
CXX_FLAGS += -D__MBED_CMSIS_RTOS_CM
CXX_FLAGS += -DDEVICE_LOWPOWERTIMER=1
CXX_FLAGS += -DDEVICE_RTC=1
CXX_FLAGS += -DTOOLCHAIN_object
CXX_FLAGS += -DDEVICE_SERIAL_ASYNCH=1
CXX_FLAGS += -D__CMSIS_RTOS
CXX_FLAGS += -DTARGET_MCU_NRF51822_UNIFIED
CXX_FLAGS += -DTOOLCHAIN_GCC
CXX_FLAGS += -DDEVICE_I2C_ASYNCH=1
CXX_FLAGS += -DTARGET_CORTEX_M
CXX_FLAGS += -DTARGET_SDK11
CXX_FLAGS += -DARM_MATH_CM0
CXX_FLAGS += -DTARGET_UVISOR_UNSUPPORTED
CXX_FLAGS += -DTARGET_NRF5
CXX_FLAGS += -DFEATURE_BLE=1
CXX_FLAGS += -DTARGET_M0
CXX_FLAGS += -DTARGET_MCU_NRF51
CXX_FLAGS += -DCMSIS_VECTAB_VIRTUAL
CXX_FLAGS += -DTARGET_MCU_NRF51_UNIFIED
CXX_FLAGS += -DMBED_TICKLESS
CXX_FLAGS += -DDEVICE_INTERRUPTIN=1
CXX_FLAGS += -DTARGET_CORTEX
CXX_FLAGS += -DDEVICE_I2C=1
CXX_FLAGS += -DDEVICE_PORTOUT=1
CXX_FLAGS += -DDEVICE_SERIAL=1
CXX_FLAGS += -DDEVICE_SPI_ASYNCH=1
CXX_FLAGS += -DTARGET_FF_ARDUINO
CXX_FLAGS += -DDEVICE_PORTIN=1
CXX_FLAGS += -DTARGET_RELEASE
CXX_FLAGS += -DTARGET_NORDIC
CXX_FLAGS += -DDEVICE_SERIAL_FC=1
CXX_FLAGS += -DBLE_STACK_SUPPORT_REQD
CXX_FLAGS += -DTARGET_MCU_NRF51_32K_UNIFIED
CXX_FLAGS += -DTARGET_NRF51_DK
CXX_FLAGS += -DDEVICE_SLEEP=1
CXX_FLAGS += -DTOOLCHAIN_GCC_ARM
CXX_FLAGS += -DTARGET_MCU_NRF51822
CXX_FLAGS += -DMBED_BUILD_TIMESTAMP=1515055061.66
CXX_FLAGS += -DTARGET_MCU_NORDIC_32K
CXX_FLAGS += -DSOFTDEVICE_PRESENT
CXX_FLAGS += -DNO_SYSTICK
CXX_FLAGS += -DDEVICE_SPI=1
CXX_FLAGS += -DCMSIS_VECTAB_VIRTUAL_HEADER_FILE=\"cmsis_nvic.h\"
CXX_FLAGS += -DDEVICE_SPISLAVE=1
CXX_FLAGS += -DDEVICE_ANALOGIN=1
CXX_FLAGS += -DDEVICE_PWMOUT=1
CXX_FLAGS += -DS130
CXX_FLAGS += -DTARGET_LIKE_CORTEX_M0
CXX_FLAGS += -DTARGET_MCU_NRF51_32K
CXX_FLAGS += -include
CXX_FLAGS += mbed_config.h

ASM_FLAGS += -x
ASM_FLAGS += assembler-with-cpp
ASM_FLAGS += -D__CORTEX_M0
ASM_FLAGS += -DTARGET_MCU_NRF51_32K
ASM_FLAGS += -DTARGET_MCU_NRF51822
ASM_FLAGS += -DTARGET_MCU_NORDIC_32K
ASM_FLAGS += -DSOFTDEVICE_PRESENT
ASM_FLAGS += -DNRF51
ASM_FLAGS += -DNO_SYSTICK
ASM_FLAGS += -DTARGET_NRF51822
ASM_FLAGS += -DARM_MATH_CM0
ASM_FLAGS += -D__MBED_CMSIS_RTOS_CM
ASM_FLAGS += -DCMSIS_VECTAB_VIRTUAL
ASM_FLAGS += -DCMSIS_VECTAB_VIRTUAL_HEADER_FILE=\"cmsis_nvic.h\"
ASM_FLAGS += -DBLE_STACK_SUPPORT_REQD
ASM_FLAGS += -D__CMSIS_RTOS
ASM_FLAGS += -DMBED_TICKLESS
ASM_FLAGS += -DS130
ASM_FLAGS += -I.
ASM_FLAGS += -Iimg
ASM_FLAGS += -Ishields
ASM_FLAGS += -Isource
ASM_FLAGS += -Imbed-os/.
ASM_FLAGS += -Imbed-os/features
ASM_FLAGS += -Imbed-os/features/frameworks
ASM_FLAGS += -Imbed-os/features/frameworks/greentea-client
ASM_FLAGS += -Imbed-os/features/frameworks/greentea-client/greentea-client
ASM_FLAGS += -Imbed-os/features/frameworks/greentea-client/source
ASM_FLAGS += -Imbed-os/features/frameworks/unity
ASM_FLAGS += -Imbed-os/features/frameworks/unity/source
ASM_FLAGS += -Imbed-os/features/frameworks/unity/unity
ASM_FLAGS += -Imbed-os/features/frameworks/utest
ASM_FLAGS += -Imbed-os/features/frameworks/utest/source
ASM_FLAGS += -Imbed-os/features/frameworks/utest/utest
ASM_FLAGS += -Imbed-os/features/mbedtls
ASM_FLAGS += -Imbed-os/features/mbedtls/importer
ASM_FLAGS += -Imbed-os/features/mbedtls/inc
ASM_FLAGS += -Imbed-os/features/mbedtls/inc/mbedtls
ASM_FLAGS += -Imbed-os/features/mbedtls/src
ASM_FLAGS += -Imbed-os/features/mbedtls/platform
ASM_FLAGS += -Imbed-os/features/mbedtls/platform/inc
ASM_FLAGS += -Imbed-os/features/mbedtls/platform/src
ASM_FLAGS += -Imbed-os/features/mbedtls/targets
ASM_FLAGS += -Imbed-os/features/nanostack
ASM_FLAGS += -Imbed-os/features/storage
ASM_FLAGS += -Imbed-os/features/netsocket
ASM_FLAGS += -Imbed-os/features/netsocket/cellular
ASM_FLAGS += -Imbed-os/features/netsocket/cellular/generic_modem_driver
ASM_FLAGS += -Imbed-os/features/netsocket/cellular/utils
ASM_FLAGS += -Imbed-os/features/filesystem
ASM_FLAGS += -Imbed-os/features/filesystem/bd
ASM_FLAGS += -Imbed-os/features/filesystem/fat
ASM_FLAGS += -Imbed-os/features/filesystem/fat/ChaN
ASM_FLAGS += -Imbed-os/features/filesystem/littlefs
ASM_FLAGS += -Imbed-os/features/filesystem/littlefs/TESTS_COMMON
ASM_FLAGS += -Imbed-os/features/filesystem/littlefs/littlefs
ASM_FLAGS += -Imbed-os/cmsis
ASM_FLAGS += -Imbed-os/cmsis/TARGET_CORTEX_M
ASM_FLAGS += -Imbed-os/drivers
ASM_FLAGS += -Imbed-os/events
ASM_FLAGS += -Imbed-os/events/equeue
ASM_FLAGS += -Imbed-os/rtos
ASM_FLAGS += -Imbed-os/rtos/TARGET_CORTEX
ASM_FLAGS += -Imbed-os/rtos/TARGET_CORTEX/rtx4
ASM_FLAGS += -Imbed-os/rtos/TARGET_CORTEX/rtx5
ASM_FLAGS += -Imbed-os/rtos/TARGET_CORTEX/rtx5/Include
ASM_FLAGS += -Imbed-os/rtos/TARGET_CORTEX/rtx5/RTX
ASM_FLAGS += -Imbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Config
ASM_FLAGS += -Imbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Include
ASM_FLAGS += -Imbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source
ASM_FLAGS += -Imbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_GCC
ASM_FLAGS += -Imbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_GCC/TARGET_M0
ASM_FLAGS += -Imbed-os/rtos/TARGET_CORTEX/rtx5/Source
ASM_FLAGS += -Imbed-os/hal
ASM_FLAGS += -Imbed-os/hal/storage_abstraction
ASM_FLAGS += -Imbed-os/platform
ASM_FLAGS += -Imbed-os/targets
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/TARGET_NRF51_DK
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/device
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/device/TOOLCHAIN_GCC_ARM
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/device/TOOLCHAIN_GCC_ARM/TARGET_MCU_NORDIC_32K
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/sdk
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/sdk/drivers_nrf
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/sdk/drivers_nrf/adc
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/sdk/softdevice
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/sdk/softdevice/s130
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/sdk/softdevice/s130/headers
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/sdk/softdevice/s130/headers/nrf51
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/sdk/softdevice/s130/hex
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/sdk_patch
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/ble_advertising
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/ble_db_discovery
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/ble_debug_assert_handler
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/ble_dtm
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/ble_error_log
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/ble_racp
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/ble_radio_notification
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/ble_services
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/ble_services/ble_dfu
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/common
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/device_manager
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/device_manager/config
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/ble/peer_manager
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/device
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/ble_flash
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/clock
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/common
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/config
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/delay
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/gpiote
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/hal
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/ppi
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/pstorage
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/pstorage/config
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/spi_master
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/spi_slave
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/timer
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/bootloader_dfu
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/bootloader_dfu/hci_transport
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/crc16
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/experimental_section_vars
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/fds
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/fds/config
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/fstorage
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/fstorage/config
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/hci
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/hci/config
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/pwm
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/scheduler
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/trace
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/libraries/util
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/softdevice
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/softdevice/common
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/softdevice/common/softdevice_handler
ASM_FLAGS += -Imbed-os/targets/TARGET_NORDIC/TARGET_NRF5/porting_tools
ASM_FLAGS += -Imbed-os/features/FEATURE_BLE
ASM_FLAGS += -Imbed-os/features/FEATURE_BLE/ble
ASM_FLAGS += -Imbed-os/features/FEATURE_BLE/ble/services
ASM_FLAGS += -Imbed-os/features/FEATURE_BLE/ble/generic
ASM_FLAGS += -Imbed-os/features/FEATURE_BLE/ble/pal
ASM_FLAGS += -Imbed-os/features/FEATURE_BLE/source
ASM_FLAGS += -Imbed-os/features/FEATURE_BLE/source/services
ASM_FLAGS += -Imbed-os/features/FEATURE_BLE/source/generic
ASM_FLAGS += -Imbed-os/features/FEATURE_BLE/targets
ASM_FLAGS += -Imbed-os/features/FEATURE_BLE/targets/TARGET_NORDIC
ASM_FLAGS += -Imbed-os/features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5
ASM_FLAGS += -Imbed-os/features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source
ASM_FLAGS += -Imbed-os/features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source/btle
ASM_FLAGS += -Imbed-os/features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source/btle/custom
ASM_FLAGS += -Imbed-os/features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source/common


LD_FLAGS :=-Wl,--gc-sections -Wl,--wrap,main -Wl,--wrap,_malloc_r -Wl,--wrap,_free_r -Wl,--wrap,_realloc_r -Wl,--wrap,_memalign_r -Wl,--wrap,_calloc_r -Wl,--wrap,exit -Wl,--wrap,atexit -Wl,-n -mcpu=cortex-m0 -mthumb 
LD_SYS_LIBS :=-Wl,--start-group -lstdc++ -lsupc++ -lm -lc -lgcc -lnosys  -Wl,--end-group

# Tools and Flags
###############################################################################
# Rules

.PHONY: all lst size

all: $(PROJECT).bin $(PROJECT)-combined.hex size


.s.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Assemble: $(notdir $<)"
  
	@$(AS) -c $(ASM_FLAGS) -o $@ $<
  


.S.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Assemble: $(notdir $<)"
  
	@$(AS) -c $(ASM_FLAGS) -o $@ $<
  

.c.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Compile: $(notdir $<)"
	@$(CC) $(C_FLAGS) $(INCLUDE_PATHS) -o $@ $<

.cpp.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Compile: $(notdir $<)"
	@$(CPP) $(CXX_FLAGS) $(INCLUDE_PATHS) -o $@ $<


$(PROJECT).link_script.ld: $(LINKER_SCRIPT)
	@$(PREPROC) $< -o $@



$(PROJECT).elf: $(OBJECTS) $(SYS_OBJECTS) $(PROJECT).link_script.ld 
	+@echo "link: $(notdir $@)"
	@$(LD) $(LD_FLAGS) -T $(filter-out %.o, $^) $(LIBRARY_PATHS) --output $@ $(filter %.o, $^) $(LIBRARIES) $(LD_SYS_LIBS)


$(PROJECT).bin: $(PROJECT).elf
	$(ELF2BIN) -O binary $< $@


$(PROJECT).hex: $(PROJECT).elf
	$(ELF2BIN) -O ihex $< $@

SOFTDEVICE = ../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/sdk/softdevice/s130/hex/s130_nrf51_2.0.0_softdevice.hex

# For Debug or NoDebug
ifeq ($(DEBUG), 1)
  C_FLAGS += -DDEBUG -O0 -g3
  CXX_FLAGS += -DDEBUG -O0 -g3
else
  C_FLAGS += -DNDEBUG -Os
  CXX_FLAGS += -DNDEBUG -Os
endif


$(PROJECT)-combined.hex: $(PROJECT).hex
	+@echo "NOTE: the $(SREC_CAT) binary is required to be present in your PATH. Please see http://srecord.sourceforge.net/ for more information."
#	$(SREC_CAT) ../mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/sdk/softdevice/s130/hex/s130_nrf51_2.0.0_softdevice.hex  -intel $(PROJECT).hex -intel -o $(PROJECT)-combined.hex -intel --line-length=44
	mergehex -m $(SOFTDEVICE) $(PROJECT).hex -o combined.hex
	+@echo "===== hex file ready to flash: $(OBJDIR)/$@ ====="

# Rules
###############################################################################
# Dependencies

DEPS = $(OBJECTS:.o=.d) $(SYS_OBJECTS:.o=.d)
-include $(DEPS)
endif

# Dependencies
###############################################################################
